@startuml
!include .\\Caretaker.puml
!include .\\Memento.puml
!include .\\Program.puml
!include .\\Shape.puml
!include .\\obj\Debug\net6.0\.NETCoreApp,Version=v6.0.AssemblyAttributes.puml
!include .\\obj\Debug\net6.0\Assingment03Split.AssemblyInfo.puml
!include .\\obj\Debug\net6.0\Assingment03Split.GlobalUsings.g.puml
!include .\\obj\Debug\net6.0\Worm.AssemblyInfo.puml
!include .\\obj\Debug\net6.0\Worm.GlobalUsings.g.puml
@enduml
