@startuml
class Program {
    {static} Main(args:string[]) : void
    + {static} addShape(str:string, Canvas:List<Shape>) : void
    {static} printCurrentSVG(Canvas:List<Shape>) : void
    + {static} createSVG(Shape:List<Shape>) : string
    {static} undoShapeCanvas(Canvas:List<Shape>, CareUndoRedo:Caretaker) : void
    {static} redoShapeCanvas(Canvas:List<Shape>, CareUndoRedo:Caretaker) : void
}
@enduml
