@startuml
class Caretaker {
    + getState() : Memento
    + addState(m:Memento) : void
    + getSize() : int
}
class "List`1"<T> {
}
Caretaker o-> "CareUndoRedo<Memento>" "List`1"
Caretaker o-> "state" Memento
@enduml
